version: '3.9'
services:
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=nileapp
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=osw4l
    ports:
       - "6543:5432"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/nile"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: nileapp
      DB_PASSWORD: osw4l
      DB_HOST: db